"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 03:53:51.729237
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_tenant_time', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_table('companies',
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_canonical_name'), 'companies', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('concepts',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['concepts.id'], name=op.f('fk_concepts_parent_id_concepts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts'))
    )
    op.create_index('ix_concepts_kind_name', 'concepts', ['kind', 'canonical_name'], unique=False)
    op.create_index(op.f('ix_concepts_tenant_id'), 'concepts', ['tenant_id'], unique=False)
    op.create_table('connector_configs',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=60), nullable=False),
    sa.Column('adapter_version', sa.String(length=20), nullable=False),
    sa.Column('rate_limit_per_sec', sa.Float(), nullable=False),
    sa.Column('freshness_slo_hours', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_configs')),
    sa.UniqueConstraint('key', name=op.f('uq_connector_configs_key'))
    )
    op.create_table('connector_runs',
    sa.Column('connector_key', sa.String(length=40), nullable=False),
    sa.Column('adapter_version', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('changes_emitted', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_runs'))
    )
    op.create_index('ix_runs_key_started', 'connector_runs', ['connector_key', 'started_at'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('alias_norm', sa.String(length=300), nullable=False),
    sa.Column('alias_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_type', 'alias_norm', 'entity_id', 'tenant_id', name=op.f('uq_entity_aliases_entity_type_alias_norm_entity_id_tenant_id'))
    )
    op.create_index('ix_alias_norm', 'entity_aliases', ['alias_norm'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_tenant_id'), 'entity_aliases', ['tenant_id'], unique=False)
    op.create_table('entity_links',
    sa.Column('mention', sa.String(length=300), nullable=False),
    sa.Column('mention_norm', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('context_type', sa.String(length=30), nullable=True),
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_links'))
    )
    op.create_index(op.f('ix_entity_links_mention_norm'), 'entity_links', ['mention_norm'], unique=False)
    op.create_index('ix_entity_links_status', 'entity_links', ['status'], unique=False)
    op.create_index(op.f('ix_entity_links_tenant_id'), 'entity_links', ['tenant_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('key', 'tenant_id', name=op.f('uq_feature_flags_key_tenant_id'))
    )
    op.create_table('feedback_datasets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('records', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_datasets')),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name=op.f('uq_feedback_datasets_tenant_id_name_version'))
    )
    op.create_index(op.f('ix_feedback_datasets_tenant_id'), 'feedback_datasets', ['tenant_id'], unique=False)
    op.create_table('generation_records',
    sa.Column('workflow', sa.String(length=60), nullable=False),
    sa.Column('workflow_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_id', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('served_model', sa.String(length=80), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_set_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('stop_reason', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_records'))
    )
    op.create_index(op.f('ix_generation_records_tenant_id'), 'generation_records', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'tenant_id', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('landscape_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('therapeutic_area', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landscape_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_landscape_templates_name'))
    )
    op.create_table('notified_event_state',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('intel_event_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'policy_id', 'intel_event_id', name=op.f('pk_notified_event_state'))
    )
    op.create_table('profile_field_definitions',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('entity_ids_kind', sa.String(length=30), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_field_definitions')),
    sa.UniqueConstraint('tenant_id', 'key', name=op.f('uq_profile_field_definitions_tenant_id_key'))
    )
    op.create_index(op.f('ix_profile_field_definitions_tenant_id'), 'profile_field_definitions', ['tenant_id'], unique=False)
    op.create_table('relationships',
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=40), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('subject_id', 'predicate', 'object_id', 'tenant_id', 'valid_from', name=op.f('uq_relationships_subject_id_predicate_object_id_tenant_id_valid_from'))
    )
    op.create_index('ix_rel_object', 'relationships', ['object_id', 'predicate'], unique=False)
    op.create_index('ix_rel_subject', 'relationships', ['subject_id', 'predicate'], unique=False)
    op.create_index(op.f('ix_relationships_tenant_id'), 'relationships', ['tenant_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('view', sa.String(length=30), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views'))
    )
    op.create_index(op.f('ix_saved_views_owner_id'), 'saved_views', ['owner_id'], unique=False)
    op.create_index(op.f('ix_saved_views_tenant_id'), 'saved_views', ['tenant_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_object_id', sa.String(length=200), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_last_updated', sa.String(length=40), nullable=True),
    sa.Column('connector_key', sa.String(length=40), nullable=False),
    sa.Column('connector_version', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('rights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('source', 'source_object_id', 'checksum', name=op.f('uq_source_documents_source_source_object_id_checksum'))
    )
    op.create_index('ix_srcdoc_object', 'source_documents', ['source', 'source_object_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deployment_mode', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('usage_records',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('component', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_units', sa.Integer(), nullable=False),
    sa.Column('output_units', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('external_subject', sa.String(length=300), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id_email'))
    )
    op.create_index(op.f('ix_users_external_subject'), 'users', ['external_subject'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('owner_company_id', sa.UUID(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('modality', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_company_id'], ['companies.id'], name=op.f('fk_assets_owner_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_canonical_name'), 'assets', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('disclosures',
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('form_type', sa.String(length=40), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_disclosures_company_id_companies')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_disclosures_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosures')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_disclosures_dedupe_key'))
    )
    op.create_table('landscapes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disease', sa.String(length=200), nullable=True),
    sa.Column('indication_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('mechanism_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('biomarker_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('geographies', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['landscape_templates.id'], name=op.f('fk_landscapes_template_id_landscape_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landscapes')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_landscapes_tenant_id_name'))
    )
    op.create_index(op.f('ix_landscapes_tenant_id'), 'landscapes', ['tenant_id'], unique=False)
    op.create_table('model_releases',
    sa.Column('component', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promoted_by', sa.String(length=100), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['feedback_datasets.id'], name=op.f('fk_model_releases_dataset_id_feedback_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_releases'))
    )
    op.create_index(op.f('ix_model_releases_tenant_id'), 'model_releases', ['tenant_id'], unique=False)
    op.create_table('publications',
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('query_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_publications_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications')),
    sa.UniqueConstraint('pmid', name=op.f('uq_publications_pmid'))
    )
    op.create_index(op.f('ix_publications_doi'), 'publications', ['doi'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_object_id', sa.String(length=200), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_last_updated', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_source_snapshots_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots')),
    sa.UniqueConstraint('object_type', 'object_id', 'version', name=op.f('uq_source_snapshots_object_type_object_id_version'))
    )
    op.create_index('ix_snapshot_object', 'source_snapshots', ['object_type', 'object_id', 'version'], unique=False)
    op.create_table('trials',
    sa.Column('nct_id', sa.String(length=20), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sponsor_company_id', sa.UUID(), nullable=True),
    sa.Column('sponsor_name', sa.String(length=300), nullable=True),
    sa.Column('phase', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('primary_completion_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('current', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_company_id'], ['companies.id'], name=op.f('fk_trials_sponsor_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trials')),
    sa.UniqueConstraint('nct_id', name=op.f('uq_trials_nct_id'))
    )
    op.create_table('ask_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('landscape_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_ask_sessions_landscape_id_landscapes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ask_sessions'))
    )
    op.create_index(op.f('ix_ask_sessions_tenant_id'), 'ask_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ask_sessions_user_id'), 'ask_sessions', ['user_id'], unique=False)
    op.create_table('asset_profile_versions',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_profile_versions_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_profile_versions')),
    sa.UniqueConstraint('asset_id', 'version', name=op.f('uq_asset_profile_versions_asset_id_version'))
    )
    op.create_index(op.f('ix_asset_profile_versions_asset_id'), 'asset_profile_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_profile_versions_tenant_id'), 'asset_profile_versions', ['tenant_id'], unique=False)
    op.create_table('catalysts',
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('trial_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('date_basis', sa.String(length=20), nullable=False),
    sa.Column('date_precision', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_catalysts_asset_id_assets')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_catalysts_company_id_companies')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_catalysts_source_document_id_source_documents')),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], name=op.f('fk_catalysts_trial_id_trials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalysts')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_catalysts_dedupe_key'))
    )
    op.create_index(op.f('ix_catalysts_asset_id'), 'catalysts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_catalysts_expected_date'), 'catalysts', ['expected_date'], unique=False)
    op.create_index(op.f('ix_catalysts_tenant_id'), 'catalysts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_catalysts_trial_id'), 'catalysts', ['trial_id'], unique=False)
    op.create_table('change_events',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('secondary_tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('magnitude', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('from_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('to_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.String(length=200), nullable=True),
    sa.Column('source_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_change_events_from_snapshot_id_source_snapshots')),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_change_events_to_snapshot_id_source_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_events')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_change_events_fingerprint'))
    )
    op.create_index(op.f('ix_change_events_change_type'), 'change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_events_processed'), 'change_events', ['processed'], unique=False)
    op.create_index('ix_change_object', 'change_events', ['object_type', 'object_id', 'detected_at'], unique=False)
    op.create_table('document_chunks',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('field_path', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || text)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], name=op.f('fk_document_chunks_snapshot_id_source_snapshots')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_document_chunks_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('source_document_id', 'chunk_index', 'embedding_model', name=op.f('uq_document_chunks_source_document_id_chunk_index_embedding_model'))
    )
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_entities', 'document_chunks', ['entity_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_object', 'document_chunks', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_chunks_tsv', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_is_current'), 'document_chunks', ['is_current'], unique=False)
    op.create_index(op.f('ix_document_chunks_published_at'), 'document_chunks', ['published_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_source'), 'document_chunks', ['source'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_document_id'), 'document_chunks', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_tenant_id'), 'document_chunks', ['tenant_id'], unique=False)
    op.create_table('intelligence_events',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('landscape_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('primary_type', sa.String(length=40), nullable=False),
    sa.Column('secondary_tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('change_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('related_entity_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('facet_terms', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('impacted_asset_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('impacted_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('materiality_score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=30), nullable=False),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('update_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_narrative_id', sa.UUID(), nullable=True),
    sa.Column('publication_blocked_reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_eligible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_intelligence_events_landscape_id_landscapes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_events')),
    sa.UniqueConstraint('tenant_id', 'fingerprint', name=op.f('uq_intelligence_events_tenant_id_fingerprint'))
    )
    op.create_index('ix_intel_facets', 'intelligence_events', ['facet_terms'], unique=False, postgresql_using='gin')
    op.create_index('ix_intel_tenant_detected', 'intelligence_events', ['tenant_id', 'detected_at'], unique=False)
    op.create_index('ix_intel_tenant_score', 'intelligence_events', ['tenant_id', 'materiality_score'], unique=False)
    op.create_index(op.f('ix_intelligence_events_asset_id'), 'intelligence_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_company_id'), 'intelligence_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_landscape_id'), 'intelligence_events', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_tenant_id'), 'intelligence_events', ['tenant_id'], unique=False)
    op.create_table('landscape_members',
    sa.Column('landscape_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_landscape_members_landscape_id_landscapes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landscape_members')),
    sa.UniqueConstraint('landscape_id', 'entity_type', 'entity_id', name=op.f('uq_landscape_members_landscape_id_entity_type_entity_id'))
    )
    op.create_index(op.f('ix_landscape_members_entity_id'), 'landscape_members', ['entity_id'], unique=False)
    op.create_index(op.f('ix_landscape_members_landscape_id'), 'landscape_members', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_landscape_members_tenant_id'), 'landscape_members', ['tenant_id'], unique=False)
    op.create_table('proximity_rules',
    sa.Column('landscape_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_proximity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_proximity_rules_landscape_id_landscapes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proximity_rules'))
    )
    op.create_index(op.f('ix_proximity_rules_tenant_id'), 'proximity_rules', ['tenant_id'], unique=False)
    op.create_table('regulatory_events',
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('agency', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('application_number', sa.String(length=40), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_regulatory_events_asset_id_assets')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_regulatory_events_source_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_events')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_regulatory_events_dedupe_key'))
    )
    op.create_index(op.f('ix_regulatory_events_application_number'), 'regulatory_events', ['application_number'], unique=False)
    op.create_table('watchlists',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('landscape_id', sa.UUID(), nullable=True),
    sa.Column('alert_policy_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_watchlists_landscape_id_landscapes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists'))
    )
    op.create_index(op.f('ix_watchlists_owner_id'), 'watchlists', ['owner_id'], unique=False)
    op.create_index(op.f('ix_watchlists_tenant_id'), 'watchlists', ['tenant_id'], unique=False)
    op.create_table('alert_policies',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('landscape_id', sa.UUID(), nullable=True),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('event_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('entity_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=True),
    sa.Column('channels', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('destinations_encrypted', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_alert_policies_landscape_id_landscapes')),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_alert_policies_watchlist_id_watchlists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_policies'))
    )
    op.create_index(op.f('ix_alert_policies_owner_id'), 'alert_policies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_alert_policies_tenant_id'), 'alert_policies', ['tenant_id'], unique=False)
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('intel_event_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('band_at_feedback', sa.String(length=30), nullable=True),
    sa.Column('score_at_feedback', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intel_event_id'], ['intelligence_events.id'], name=op.f('fk_feedback_intel_event_id_intelligence_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index('ix_feedback_event', 'feedback', ['tenant_id', 'intel_event_id'], unique=False)
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    op.create_table('generated_artifacts',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('intel_event_id', sa.UUID(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('validation_generation_id', sa.UUID(), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publishable', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('is_human_edited', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.Column('edit_reason', sa.Text(), nullable=True),
    sa.Column('model_workflow_version', sa.String(length=80), nullable=False),
    sa.Column('evidence_snapshot_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generation_records.id'], name=op.f('fk_generated_artifacts_generation_id_generation_records')),
    sa.ForeignKeyConstraint(['intel_event_id'], ['intelligence_events.id'], name=op.f('fk_generated_artifacts_intel_event_id_intelligence_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_artifacts'))
    )
    op.create_index(op.f('ix_generated_artifacts_intel_event_id'), 'generated_artifacts', ['intel_event_id'], unique=False)
    op.create_index(op.f('ix_generated_artifacts_tenant_id'), 'generated_artifacts', ['tenant_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'item_type', 'entity_id', 'value', name=op.f('uq_watchlist_items_watchlist_id_item_type_entity_id_value'))
    )
    op.create_index(op.f('ix_watchlist_items_tenant_id'), 'watchlist_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('ask_turns',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('resolved_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['generated_artifacts.id'], name=op.f('fk_ask_turns_artifact_id_generated_artifacts')),
    sa.ForeignKeyConstraint(['session_id'], ['ask_sessions.id'], name=op.f('fk_ask_turns_session_id_ask_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ask_turns'))
    )
    op.create_index(op.f('ix_ask_turns_session_id'), 'ask_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_ask_turns_tenant_id'), 'ask_turns', ['tenant_id'], unique=False)
    op.create_table('claims',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('intel_event_id', sa.UUID(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('statement_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_entities', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_statement_type', sa.String(length=30), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_workflow_version', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['generated_artifacts.id'], name=op.f('fk_claims_artifact_id_generated_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_artifact_id'), 'claims', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_claims_intel_event_id'), 'claims', ['intel_event_id'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('intel_event_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['alert_policies.id'], name=op.f('fk_notifications_policy_id_alert_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('tenant_id', 'dedupe_key', name=op.f('uq_notifications_tenant_id_dedupe_key'))
    )
    op.create_index('ix_notif_status', 'notifications', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('landscape_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('edited_artifact_id', sa.UUID(), nullable=True),
    sa.Column('distribution_list', postgresql.ARRAY(sa.String(length=320)), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['generated_artifacts.id'], name=op.f('fk_reports_artifact_id_generated_artifacts')),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], name=op.f('fk_reports_landscape_id_landscapes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_landscape_id'), 'reports', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_landscape_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index('ix_notif_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_intel_event_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_artifact_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_ask_turns_tenant_id'), table_name='ask_turns')
    op.drop_index(op.f('ix_ask_turns_session_id'), table_name='ask_turns')
    op.drop_table('ask_turns')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_tenant_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_generated_artifacts_tenant_id'), table_name='generated_artifacts')
    op.drop_index(op.f('ix_generated_artifacts_intel_event_id'), table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_index('ix_feedback_event', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_alert_policies_tenant_id'), table_name='alert_policies')
    op.drop_index(op.f('ix_alert_policies_owner_id'), table_name='alert_policies')
    op.drop_table('alert_policies')
    op.drop_index(op.f('ix_watchlists_tenant_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_owner_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_regulatory_events_application_number'), table_name='regulatory_events')
    op.drop_table('regulatory_events')
    op.drop_index(op.f('ix_proximity_rules_tenant_id'), table_name='proximity_rules')
    op.drop_table('proximity_rules')
    op.drop_index(op.f('ix_landscape_members_tenant_id'), table_name='landscape_members')
    op.drop_index(op.f('ix_landscape_members_landscape_id'), table_name='landscape_members')
    op.drop_index(op.f('ix_landscape_members_entity_id'), table_name='landscape_members')
    op.drop_table('landscape_members')
    op.drop_index(op.f('ix_intelligence_events_tenant_id'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_landscape_id'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_company_id'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_asset_id'), table_name='intelligence_events')
    op.drop_index('ix_intel_tenant_score', table_name='intelligence_events')
    op.drop_index('ix_intel_tenant_detected', table_name='intelligence_events')
    op.drop_index('ix_intel_facets', table_name='intelligence_events', postgresql_using='gin')
    op.drop_table('intelligence_events')
    op.drop_index(op.f('ix_document_chunks_tenant_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_source_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_source'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_published_at'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_is_current'), table_name='document_chunks')
    op.drop_index('ix_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_object', table_name='document_chunks')
    op.drop_index('ix_chunks_entities', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index('ix_change_object', table_name='change_events')
    op.drop_index(op.f('ix_change_events_processed'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_change_type'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_catalysts_trial_id'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_tenant_id'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_expected_date'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_asset_id'), table_name='catalysts')
    op.drop_table('catalysts')
    op.drop_index(op.f('ix_asset_profile_versions_tenant_id'), table_name='asset_profile_versions')
    op.drop_index(op.f('ix_asset_profile_versions_asset_id'), table_name='asset_profile_versions')
    op.drop_table('asset_profile_versions')
    op.drop_index(op.f('ix_ask_sessions_user_id'), table_name='ask_sessions')
    op.drop_index(op.f('ix_ask_sessions_tenant_id'), table_name='ask_sessions')
    op.drop_table('ask_sessions')
    op.drop_table('trials')
    op.drop_index('ix_snapshot_object', table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_publications_doi'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_model_releases_tenant_id'), table_name='model_releases')
    op.drop_table('model_releases')
    op.drop_index(op.f('ix_landscapes_tenant_id'), table_name='landscapes')
    op.drop_table('landscapes')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_canonical_name'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('tenants')
    op.drop_index('ix_srcdoc_object', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_saved_views_tenant_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_owner_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_relationships_tenant_id'), table_name='relationships')
    op.drop_index('ix_rel_subject', table_name='relationships')
    op.drop_index('ix_rel_object', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_profile_field_definitions_tenant_id'), table_name='profile_field_definitions')
    op.drop_table('profile_field_definitions')
    op.drop_table('notified_event_state')
    op.drop_table('landscape_templates')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_generation_records_tenant_id'), table_name='generation_records')
    op.drop_table('generation_records')
    op.drop_index(op.f('ix_feedback_datasets_tenant_id'), table_name='feedback_datasets')
    op.drop_table('feedback_datasets')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_entity_links_tenant_id'), table_name='entity_links')
    op.drop_index('ix_entity_links_status', table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_mention_norm'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index(op.f('ix_entity_aliases_tenant_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index('ix_alias_norm', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_runs_key_started', table_name='connector_runs')
    op.drop_table('connector_runs')
    op.drop_table('connector_configs')
    op.drop_index(op.f('ix_concepts_tenant_id'), table_name='concepts')
    op.drop_index('ix_concepts_kind_name', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_canonical_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_audit_tenant_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
